### ISSUE TITLE
Adapter sync demo : When deleted second last row and scroll to some previous 50 records,  random item gets deleted when scrolling back to bottom

### ISSUE THREAD

**Issue by pavanthakur** [angular-ui/ui-scroll#178] opened 2017-10-02 10:46 UTC
Referring to below example,
http://angular-ui.github.io/ui-scroll/demo/adapterSync/adapterSync.html

Steps to reproduce the issue
1. Modify adapterSync.js, edit "lastIndex: 125" and save the changes.
   Additionally, to easily identify missing index when compared to our item id, I have added "{{$index}}"
`<span>{{$index}} :=> </span>`
`<span>{{item.content}} <span class="uid">({{item.id}})</span></span>`
2. Run example in browser
3. Delete Item 124 (second last) record
4. Scroll up to exact Item 75 record position
5. Slowly come down to bottom record again
6. Observe carefully between Item 95 to 103, any random item 98 will be missing.
7. As you scroll to top and bottom, you will observe the sequence is disturbed and any random item is deleted and the previously deleted item is shown up.

**Actual Result:** Deleting second last row onwards, deletes any random item in between.
**Expected Result**: Only exact Item record should be deleted, no other item should get deleted.

Note : 
------
1. In above-referred demo example, the link works correctly for 40 records. For eg deleting item 39 record and scrolling up and bottom does not delete any other random record.
2. This issue is also reproducible on v1.6.x

**Comment by dhilt** [comment] 2017-10-14 14:24
@pavanthakur I was able to reproduce the issue, and I can state that the demo is buggy. Will try to fix it soon. Thanks!

**Comment by dhilt** [comment] 2017-10-24 03:31
@pavanthakur This issue revealed the problem of core Adapter-Buffer interactions. I took the time to figure this out. I think, I'm done with it  and the issue you described above is gone, but may I ask you to try the [branch code](https://github.com/angular-ui/ui-scroll/tree/buffer-first-next/dist) on your project? does it satisfies your needs? If it's okey, it will be included in the next release.

**Comment by pavanthakur** [comment] 2017-10-24 12:44
@dhilt the above delete feature I am not implementing now in our project, but I will go over this weekend on demo example and revert. Thank you.

**Comment by pavanthakur** [comment] 2017-10-25 05:55
Also, a small query I observe there are daily few changes being done to the library, when shall I test on the stable version, so I  can give you feedback accordingly.

**Comment by pavanthakur** [comment] 2017-11-12 18:43
Its working for me, sorry to revert late on to this. Thank you for the fix.

**Comment by dhilt** [comment] 2017-11-13 04:48
Closed due to v1.7.0-rc.4 has been released.

**Closed by dhilt** 2017-11-13 04:48 UTC
