### ISSUE TITLE
Average items height problem

### ISSUE THREAD

**Issue by dhilt** [angular-ui/ui-scroll#68] opened 2016-03-19 17:03 UTC
In [issue#10](https://github.com/angular-ui/ui-scroll/issues/10) we have a link to some repro -- https://github.com/AlSherif/AngularUIScrollDemo -- and I researched a problem and found out that on a big list with different height items it is possible that the actual error of average items height calculation affects process of scrolling itself. It causes infinite scrollbar jumping in some cases, the [repro](https://github.com/AlSherif/AngularUIScrollDemo) demonstrates it well.

Padding elements adjustement (Viewport.adjustPadding()) may throw us in a backward direction while we are scrolling forward.

**upd:** Another one demo -- which is more easy to run -- that shows us the same problem: https://jsfiddle.net/MartyBolton/s38zdu8c/6/. This one cames from [issue#65](https://github.com/angular-ui/ui-scroll/issues/65).

**Comment by dhilt** [comment] 2016-03-19 17:27
I tried to avoid average item height recalculation during scrolling and it doesn't work. So I developed another approach. Here the buffer item height is being cached before the item is being removed, then the precise values of padding element heights are being calculated based on cached values of heights of items that were removed from a viewport once.

I pushed some code into [paddings-branch](https://github.com/angular-ui/ui-scroll/tree/paddings) that I created for this issue. It does not break tests and it fixes the problem described above... @mfeingold could you please take a look at the branch?

**Comment by MartyBolton** [comment] 2016-03-25 03:11
Hi @dhilt I tested against my repro with random item heights and it looks like your padding-branch is working excellent!  Here's the forked repro showing fix.  
https://jsfiddle.net/MartyBolton/czf6qvmL/1/

You guys have done some great work on this component.  This is the only scroller that I found addresses my needs.  I'm thinking it is far beyond other infinite scrollers out there and I looked a a few.  Keep up the great work.
Marty

**Comment by MartyBolton** [comment] 2016-03-25 14:55
@dhilt Hey Denis, something else you fixed with padding branch.  Hard to explain but in master, FireFox scroll mouse wheel step/speed was very slow, i.e. so it would take forever to scroll one item but in the paddings branch the scroll seems normal again.  Just thought I would mention it if you heard that issue before.

**Comment by dhilt** [comment] 2016-03-25 15:16
I've never heard about such FF issue before. Btw, yes, I see that mouse wheel in FF works a bit slower than in Chrome. But when I'm trying to compare 'master' and 'paddings' scroller functionality on this FF feature I see no difference. How could you see such difference? It would be intrested to look at some repro...

**Comment by MartyBolton** [comment] 2016-03-25 15:40
@dhilt So, hard to explain.  I'm building a cordova app and use chrome for the most part and push to android for now, however when I played with how this looks in desktop, I browsed my file based www site with FF because I know FF allows it and found the scrolling was essentially a crawl with master however that was fixed with paddings.  The scroll bar looks better now too, although that previously was not an issue it just seemed to be at the bottom more.  Now it looks better.  I have not tested any of the repros with FF.  I'm pretty much targeting cross brower AND devices with Cordova so I'll try to keep you posted on stuff.  So far android web view has been same as chrome which is good, scrolling works  pretty darn good now.   For me the major issue was getting view port height to take up screen so I used a directive called fill-height.  That seems to work well but I'm thinking of going CSS route when I get time. 

I have to nice to have features if you have any ideas.

a. incorporate a drag-to-refresh option at some point.  Today I have a refresh button.  But was looking at ui-scroller (a while back) for hardware scrolling - maybe now that paddings is good, I may go back to trying that in conjunction with ui-scroll.   Or if you have any ideas.  I need to just do a pull-down refresh.

b. for isloading, I'd like to put a spinner in the line element as its loading.  Right now I use an ng-show spinner that takes up the entire page.  Ideally want to show spinner on where ui-scroll is loading new content.  Not sure if you have any plans for a callback or something for that through the adapter so I can put a spinner up on loading only items.
ttyl

**Comment by soboko** [comment] 2016-03-26 02:12
@dhilt I cherry-picked your commit into my fork of ui-scroll and I can confirm that this solved my problem - thanks! The data we're trying to display mostly consists of one-line items, with occasional 60-80 line items thrown in, and I was getting the infinite scrollbar jumping when scrolling down (not scrolling up now).

**Comment by mrova** [comment] 2016-03-29 18:56
Works for me too! But...looks like it broke https://github.com/angular-ui/ui-scroll/issues/70 :(

**Comment by dhilt** [comment] 2016-03-30 12:00
@MartyBolton thanks a lot for the explanation and your ideas! we have to think about it.

@mrova what exactly is broken here, could you give us some details on this?

**Comment by mrova** [comment] 2016-03-30 20:57
@dhilt so...
on v1.3.3 when I scroll fast back and forth empty space appears on top/bottom like on this example http://screencast.com/t/O0YkrmbDKvW
On master branch this empty space is not shown.
When merged paddings branch to master it's broken again (the empty space) but flickering is gone.

**Comment by studentIvan** [comment] 2016-04-01 10:26
@mrova do you use adapter append? I had same problem in this case and temporary solve it by commented clipBottom method

**Comment by dhilt** [comment] 2016-04-01 15:31
@mrova please try the latest code form 'paddings' branch: https://github.com/angular-ui/ui-scroll/tree/paddings/dist -- does it solve your empty space issue? if no, it would be very helpful if you give us a little repro on jsfiddle for example.

We are going to release a new version of ui.scroll right after 'paddings' updates finalizing.

**Comment by mrova** [comment] 2016-04-04 06:51
@dhilt I have it on my plate for today.

**Comment by dhilt** [comment] 2016-04-04 15:14
Btw 'paddings' has been merged into 'master'.
Soon it will be released as v1.4.1.

**Comment by MartyBolton** [comment] 2016-04-04 15:39
@dhilt Awesome Denis, you guys rock. Thanks a for working on this issue!

**Comment by mrova** [comment] 2016-04-05 06:14
@dhilt still the same. No flickering but gap is there when I scroll fast.
I'll investigate it on our site and prepare (not)working example on jsfiddle but it will be end of the week more likely.

**Closed** 2016-04-17 11:58 UTC

**Comment by dhilt** [comment] 2016-04-17 12:01
Fixed in [v1.4.1](https://github.com/angular-ui/ui-scroll/releases/tag/v1.4.1).
