### ISSUE TITLE
Handling performance issues in parent app

### ISSUE THREAD

**Issue by l3utterfly** [angular-ui/ui-scroll#133] opened 2017-01-14 07:01 UTC
When a complex directive is loaded as a repeater item, sometimes the main thread might be busy, causing the following console message to be displayed (in Chrome):

**Handling of 'mousewheel' input event was delayed for 300 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.**

After this, this plugin (ui-scroll) becomes completely unusable. It will not call the `get` function in the datasource, thus not loading anything anymore.

I am not familiar with the code enough to offer a solution, but it seems that internal calculations might be disabled or offset after this happens. Unfortunately, this issue is hard to reproduce because we need a sufficiently complex app to repro.

This could be fixed by optimising the repeater content itself in the main app to render faster so it does not block the main thread, but this is sometimes not feasible.

Additionally, I do not think ui-scroller should break completely due to a performance issue of the main app. It should continue loading all items in the datasource. It might jitter/flicker etc., but still work. It is then up to the main app to optimise its performance.

Any insights?

**Comment by dhilt** [comment] 2017-01-17 22:00
Hi @l3utterfly! Thanks for the report. I digged into the issue and found out that the cause is the Passive Event Listeners feature that was implemented in browsers half a year ago. Here is some discussion around:
http://stackoverflow.com/questions/39152877/consider-marking-event-handler-as-passive-to-make-the-page-more-responive. I could not find any js-libraries that would support this feature. The issues listed on stackoverflow are still not resolved.

By the way, I was able to reproduce the issue easily through the Chrome Dev Tools CPU throttling down: http://stackoverflow.com/a/39940727/3211932 (30 times is enough).

I will close this issue as others do in this case, but we are open to further discussion. Thanks!

**Closed by dhilt** 2017-01-17 22:00 UTC

**Comment by l3utterfly** [comment] 2017-01-17 22:37
Do you think that the ui-scroll should completely fail in this case? Is there some way we can catch the error/warning and continue calculations, albeit having reduced performance?

**Comment by dhilt** [comment] 2017-01-17 23:52
Oh, I forgot to add... Since I had reproduced the issue I haven't seen ui.scroll failure. My sample app hasn't crash. So I'm able to reproduce Chrome warning but can't reproduce ui.scroll failure!

**Comment by l3utterfly** [comment] 2017-01-18 00:23
Ok, let me see if I can post a repro. If I manage to do that, consider opening this issue again?

**Comment by dhilt** [comment] 2017-01-18 09:35
@l3utterfly Sure!
