### ISSUE TITLE
Chrome 56 automatically scrolling to bottom of page

### ISSUE THREAD

**Issue by Mike258** [angular-ui/ui-scroll#138] opened 2017-02-06 12:07 UTC
Hi,
After updating my Chrome browser I see some weird behavior when scrolling.
The scroll bar is automatically going down to the bottom of the page. I have seen this happening in my own code as well as in a example. https://rawgit.com/angular-ui/ui-scroll/master/demo/scopeDatasource/scopeDatasource.html

See the GIF below. (When the page turns white it is no longer me that is scrolling.)

Seen in Chrome 56.0.2924.87 and 56.0.2924.76.
No problems in FF and IE.
In the release notes of chrome I have found that they have added CSS position: sticky;. This may or may not cause this behavior?
https://developers.google.com/web/updates/2017/01/nic56

![chrome 56 bug](https://cloud.githubusercontent.com/assets/8820413/22646487/f4a6ba9a-ec6c-11e6-9bdd-d7225906688c.gif)

**Comment by radubl** [comment] 2017-02-10 14:36
Happens on version 56, but not on 54, from what we've experience.

**Comment by dhilt** [comment] 2017-02-10 16:25
This is because of Scroll Anchoring. This feature was introduced as experimental in Chrome 51:  

 - https://developers.google.com/web/updates/2016/04/scroll-anchoring 

and set as default in Chrome 56: 

 - https://www.chromestatus.com/feature/5700102471548928

Also there's a perfect-scrollbar plugin issue, which describes the problem and gives a solution:

 - https://github.com/noraesae/perfect-scrollbar/issues/612

So the workaround is to set "overflow-anchor: none;" to the parent element, e.g. ui-scroll-viewport if you have it in your template.

I think we should add this style-property to the ui-scroll-viewport element programmatically and update a documentation for case when the ui-scroll-viewport directive is not being used... This will be added to v1.6.1 release.

**Comment by Mike258** [comment] 2017-02-13 07:56
@dhilt, thank you for pointing out this workaround. It is working!

**Comment by dhilt** [comment] 2017-02-15 02:12
The fix is in 'master' branch. Waiting for v1.6.1 release...

**Closed** 2017-03-06 12:42 UTC

**Comment by vaibhavi3t** [comment] 2018-10-12 07:12
I am using chrome Version 69.0.3497.100 (Official Build) (64-bit)
I have the same issue. 
Each time page loads, the browser scrolls the page to bottom.
Note: The content of the page is loaded by ajax apart header section.

**Comment by dhilt** [comment] 2018-10-12 15:29
@vaibhavi3t Can you make sure that you have `overflow-anchor: none;` on the viewport element? Though I'm not sure if it's still actual... anyway we need repro of the problem, because on my 69.0.3497.100 (Official Build) (64-bit) I can't reproduce it. Maybe your problem does not relate to this issue. The best option is to create plunker/stackblitz/etc, specify the OS version and any other details that could be helpful, and open new github issue.

**Comment by decibel** [comment] 2019-02-18 19:09
This just started happening to me. I have no idea what overflow-anchor or the viewport element are. How can I fix this?

Version 72.0.3626.109 (Official Build) (64-bit) (OS X)

**Comment by shijiebei2009** [comment] 2019-05-07 10:00
> This just started happening to me. I have no idea what overflow-anchor or the viewport element are. How can I fix this?
> 
> Version 72.0.3626.109 (Official Build) (64-bit) (OS X)

So do I, my MBP also have this problem with chrome (74.0.3729.131)

**Comment by BaconCatBug** [comment] 2019-08-18 20:35
Happening to me now Version 76.0.3809.100

**Comment by dhilt** [comment] 2019-08-18 22:26
Definitely can't reproduce it on my macOS Mojave and macOS Sierra with Chrome 76. Is it really happens with, for example, [this demo](http://angular-ui.github.io/ui-scroll/demo/scopeDatasource/scopeDatasource.html)? Or [this stackblitz sample](https://stackblitz.com/edit/angular-ui-scroll-v1-7-6)?
