### ISSUE TITLE
Prevent infinite loading from buffer in hidden div?

### ISSUE THREAD

**Issue by marknadig** [angular-ui/ui-scroll#15] opened 2015-08-17 15:13 UTC
I have a angular-ui ui-scroll directive (1.3.0) living in a div that is hidden by default with an ng-show. When it is hidden, ui-scroll just keeps loading data from the datasource even though the ui-scroll-viewport's height is set. If the div is shown, it behaves correctly.

I'm sure I can solve this with an ng-if to dynamically add this to the DOM. However, I wanted the div to hide/show responsively - so driven off of css.

Any suggestions on how to have ui-scroll only load 1 page from the buffer when hidden? thank you. 

http://stackoverflow.com/questions/31996151/prevent-angular-ui-ui-scroll-from-loading-in-hidden-div

**Comment by mfeingold** [comment] 2015-08-17 15:52
@dhilt can you have a look? it used to work

**Comment by dhilt** [comment] 2015-08-17 16:00
I gave some answer on [stackoverflow](http://stackoverflow.com/a/32054542/3211932), @marknadig what do you think about it?

**Comment by marknadig** [comment] 2015-08-17 16:07
Thank you for the reply @dhilt. I had thought of that approach, and it may be my last resort. The downside is having the datasource managing/monitoring the visibility which is definitely bad from a separation of concern point of view. My goal was a responsive design where the div may or may not be initially visible based on a media query. 

I had hoped the ui-scroll directive could detect the visibility, as it is detecting the height. Since it is determining "how much data will fit", it seems like the appropriate place for that logic.

**Comment by mfeingold** [comment] 2015-08-17 16:09
It is supposed to. More than that, it used to. We broke something along the
way. I marked this as a bug and we will fix it.

**Comment by marknadig** [comment] 2015-08-17 17:12
I have a small repro case here https://github.com/marknadig/ui-scroll-test

**Comment by mfeingold** [comment] 2015-08-17 21:15
Well, I have to take it back - the part that it used to work. It looks like the root cause of the problem is that if the element has display:none it has the height of 0. That's why it would not stop requesting data. The problem with this is that with height set to 0 I do not have anything to base the dimension math - I have no way of knowing when to stop. Any idea?

**Comment by marknadig** [comment] 2015-08-17 21:35
@mfeingold in my test https://github.com/marknadig/ui-scroll-test I confirmed that
$(".scrollerViewport").height() returns 520 correctly even when the parent div is hidden (display:none).  So, jquery calculated the height correctly (related: http://stackoverflow.com/questions/3632120/jquery-height-width-and-displaynone)

**Comment by mfeingold** [comment] 2015-08-18 12:46
Well, the viewport height is not the problem. The element height is. If the scroller is visible, as elements are added the total height grows. As soon as it grows beyond the size of the viewport, the fetching stops. If all element heights are 0 the total height never grows beyond viewport height and fetching never stops. The only thing I can think at the moment is to prevent fetching if viewport is invisible.

A related issue is that as of now, to properly populate the scroller after the viewport becomes visible, you will have to manually call reload on the adapter.

**Comment by marknadig** [comment] 2015-08-18 15:38
OIC. I wonder if the scroller could infer a hidden element when the elements sizes are all 0?

Yeah, good point re: becoming visible triggering reload. For future, wonder if the scroller use a DOM mutation observer to trigger the reload when the parent element is shown.

As it is, I found that if I set the style to visibility: hidden with a width of 1px, ui-scroller will load the 1 page worth of data. When the visibility becomes visible, the user can scroll and the scroller will load.

**Comment by mfeingold** [comment] 2015-08-18 16:44
Yea, that is my thinking too. I would base that on the visibility of the viewport though, because I can think up a 'valid' use case where some of the items would have 0 height, while others do not.

As to events - DOM mutation looks good, unfortunately it is only supported in IE11. 
There is also visibilitychange event, it is supported starting with IE10

Unfortunately in our development we still need IE9. The only option I can see is polling on a timer. And I hate it

**Comment by marknadig** [comment] 2015-08-18 17:05
"Unfortunately in our development we still need IE9. .... And I hate it" - every web developer ;0

**Comment by mfeingold** [comment] 2015-08-18 23:42
@marknadig I just created a new branch with the fix preventing infinite fetch. The auto reload on visibility change and some tests still need to be implemented. so for now I will keep it in the branch. Can you have a look and see if it fixes it for you?

**Comment by dhilt** [comment] 2015-08-19 10:51
@mfeingold why should we load data into invisible viewport? isn't it abnormal (in general case)? cause we can't see it... I have another [3 lines of code](https://github.com/angular-ui/ui-scroll/compare/master...dhilt:invisible-viewport#diff-dc43fb537e3c2afb99b18c187d5d8c87R56) to prevent populating of the viewport while it's invisible; just replace *viewport.outerHeight()* with its protected version *getViewportVisibleOuterHeight()*; this approach does not complicate the logic

**Comment by mfeingold** [comment] 2015-08-19 11:45
@dhilt unfortunately it does not work if the visibility is flipped on the item not on the viewport

**Comment by marknadig** [comment] 2015-08-19 20:20
@mfeingold thanks for taking a look at this. I did run the https://raw.githubusercontent.com/angular-ui/ui-scroll/invisibleItems/src/ui-scroll.coffee through http://coffeescript.org/ and then updated this sample https://github.com/marknadig/ui-scroll-test/tree/master/Demo . Unfortunately, it still keeps calling the datasource until my breaker at index > 100.

As far as the use-case, on initial inspection it seems rare you'd want a hidden div to load any data. But, it seems with responsive designs where the div may or may not be visible that this is not unreasonable.

**Comment by mfeingold** [comment] 2015-08-21 16:13
Wow. It looks like we hit here a really freaky edge case. Here is what's happening. 

To prevent infinite load I check the height of the items in the batch. I expected that if the item is invisible, its outerheight(true) would be 0. Guess what - in your case it is not. Apparently the padding is still included even though the element itself is invisible. So in your demo the height of the (invisible) element is 8.

Now I would expect that it would stop the load when it accumulated enough 8 to fill the viewport. But here is another one - the viewport is no longer constrained. Apparently the height of the element with display:none is considered to be auto - unconstrained, despite the fact that the height is specified explcitly

The combination of this two things causes the infinite load. 

I can suggest a few workarounds, but I am scrambling how can I make this work for all reasonable scenarios.

**Comment by marknadig** [comment] 2015-08-21 16:21
Wow indeed. Thanks for investigating. Not sure the library needs to handle an edge-edge case, but would it is good to be aware of the possibility - perhaps a note in the docs? Maybe wiki. 

I'm not blocked on this. I'm using visibility: hidden and width 0px when the div is hidden/collapsed and ui-scroll behaves as expected. So, I'm worked-around now.

Thanks for investigating.

**Comment by mfeingold** [comment] 2015-08-21 16:30
One way to address this would be to relay on height rather than outerHeight to determine that an item would be invisible. Can you think of a use case when somebody would have items with 0 height and play games with padding and margins?

**Comment by marknadig** [comment] 2015-08-21 18:18
I can't. Seems reasonable.

**Closed** 2015-09-03 13:57 UTC
Labels: bug
