### ISSUE TITLE
White space issue after scroll when elements have different height

### ISSUE THREAD

**Issue by Jerczu** [angular-ui/ui-scroll#158] opened 2017-05-13 10:40 UTC
When you quick scroll up few pages and down to the very bottom especially if your items do have additional data inserted asynchronously you end up with big white space at the very bottom. It would be I guess beneficial if when  you reach EOF/BOF those paddings are forced to padding 0

**Comment by dhilt** [comment] 2017-05-13 14:12
@Jerczu We can't reset paddings cause we won't lose the knowledge of visual scroll bar parametrs. The issue you described should be fixed, and there are two possible ways: app fix or lib fix. Depends on the source of the issue. So we need to investigate it and it would be great if you provide us with a repro... right now I'm not able to reproduce that behaviour with our demos.

**Comment by dhilt** [comment] 2017-07-06 23:57
I believe this [PR#165](https://github.com/angular-ui/ui-scroll/pull/165) relates to this issue. Please try ui.scrool v1.6.2+ and feel free to reopen the issue if it doesn't fix your problem.

**Closed by dhilt** 2017-07-06 23:57 UTC
